FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY ../go.mod ../go.sum ./

RUN go mod download 

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o processnode .

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/processnode .

EXPOSE 8081

ENTRYPOINT [ "./processnode" ]